"""Layered plotting helpers for the paper-python-plots skill."""

from .styles import (
    SOFT_EDGE_EDGES,
    SOFT_EDGE_FILLS,
    SOFT_EDGE_PALETTES,
    TOP_PAPER_PALETTES,
    TOP_PAPER_STYLE_NOTES,
    WEB_INSPIRED_PALETTES,
    WEB_STYLE_NOTES,
)
from .top_paper_plots import (
    ablation_matrix_plot,
    demo_ablation_matrix,
    demo_metric_suite,
    demo_pareto_scatter,
    demo_qual_grid,
    demo_uncertainty_map,
    metric_suite_dashboard,
    pareto_scatter_plot,
    qualitative_result_grid,
    uncertainty_map_plot,
)
from .figures4papers import (
    FIGURES4PAPERS_DEFAULT_COLORS,
    FIGURES4PAPERS_PALETTE,
    Figures4PapersStyle,
    apply_figures4papers_style,
    create_subplots,
    demo_figures4papers_house_style,
    finalize_figure,
    make_grouped_bar,
    make_heatmap,
    make_scatter,
    make_sphere_illustration,
    make_trend,
)
from .nn_report_plots import (
    ablation_table_figure,
    classification_report_figure,
    demo_nn_report_figures,
    error_reduction_figure,
    training_curves_figure,
)

__all__ = [
    "TOP_PAPER_PALETTES",
    "TOP_PAPER_STYLE_NOTES",
    "WEB_INSPIRED_PALETTES",
    "WEB_STYLE_NOTES",
    "SOFT_EDGE_PALETTES",
    "SOFT_EDGE_FILLS",
    "SOFT_EDGE_EDGES",
    "ablation_matrix_plot",
    "demo_ablation_matrix",
    "demo_metric_suite",
    "demo_pareto_scatter",
    "demo_qual_grid",
    "demo_uncertainty_map",
    "metric_suite_dashboard",
    "pareto_scatter_plot",
    "qualitative_result_grid",
    "uncertainty_map_plot",
    "FIGURES4PAPERS_PALETTE",
    "FIGURES4PAPERS_DEFAULT_COLORS",
    "Figures4PapersStyle",
    "apply_figures4papers_style",
    "create_subplots",
    "finalize_figure",
    "make_grouped_bar",
    "make_trend",
    "make_heatmap",
    "make_scatter",
    "make_sphere_illustration",
    "demo_figures4papers_house_style",
    "ablation_table_figure",
    "classification_report_figure",
    "demo_nn_report_figures",
    "error_reduction_figure",
    "training_curves_figure",
]
